INSERT INTO Campus(idCampus,Nombre,Universidad_idUniversidad) VALUES (1,'Ensenada',1);
INSERT INTO Campus(idCampus,Nombre,Universidad_idUniversidad) VALUES (2,'Mexicali',1);
INSERT INTO Campus(idCampus,Nombre,Universidad_idUniversidad) VALUES (3,'Tijuana',1);
INSERT INTO Campus(idCampus,Nombre,Universidad_idUniversidad) VALUES (4,'Mexicali',3);
INSERT INTO Campus(idCampus,Nombre,Universidad_idUniversidad) VALUES (5,'Tijuana',4);
INSERT INTO Campus(idCampus,Nombre,Universidad_idUniversidad) VALUES (6,'Ensenada',5);
INSERT INTO Campus(idCampus,Nombre,Universidad_idUniversidad) VALUES (7,'Tijuana',6);
INSERT INTO Campus(idCampus,Nombre,Universidad_idUniversidad) VALUES (8,'Ensenada',6);
INSERT INTO Campus(idCampus,Nombre,Universidad_idUniversidad) VALUES (9,'San Quintin',6);
INSERT INTO Campus(idCampus,Nombre,Universidad_idUniversidad) VALUES (1000,'Tijuana',1000);
INSERT INTO Campus(idCampus,Nombre,Universidad_idUniversidad) VALUES (1001,'Rosarito',1000);