INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (1,1,'Aguascalientes');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (2,2,'Baja California');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (3,3,'Baja California Sur');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (4,4,'Campeche');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (5,5,'Chiapas');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (6,6,'Chihuahua');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (7,7,'Coahuila');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (8,8,'Colima');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (9,9,'Ciudad de México');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (10,10,'Durango');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (11,11,'Guanajuato');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (12,12,'Guerrero');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (13,13,'Hidalgo');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (14,14,'Jalisco');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (15,15,'Estado de México');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (16,16,'Michoacán');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (17,17,'Morelos');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (18,18,'Nayarit');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (19,19,'Nuevo León');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (20,20,'Oaxaca');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (21,21,'Puebla');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (22,22,'Querétaro');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (23,23,'Quintana Roo');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (24,24,'San Luis Potosí');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (25,25,'Sinaloa');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (26,26,'Sonora');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (27,27,'Tabasco');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (28,28,'Tamaulipas');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (29,29,'Tlaxcala');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (30,30,'Veracruz');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (31,31,'Yucatán');
INSERT INTO Estado(idEstado,Numero,Nombre) VALUES (32,32,'Zacatecas');
