INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (1,'Escuela de Ciencias de la Salud',1);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (2,'Facultad de Artes (extensión Ensenada)',1);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (3,'Facultad de Ciencias',1);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (4,'Facultad de Ciencias Administrativas y Social',1);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (5,'Facultad de Ciencias Marinas',1);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (6,'Facultad de Deportes (extensión Ensenada)',1);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (7,'Facultad de Enología y Gastronomía',1);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (8,'Facultad de Idiomas (extensión Ensenada)',1);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (9,'Facultad de Ingeniería y Negocios - San Quint',1);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (10,'Facultad de Ingeniería, Arquitectura y Diseño',1);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (11,'Instituto de Investigación y Desarrollo Educa',1);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (12,'Instituto de Investigaciones Oceanológicas',1);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (13,'Facultad de Arquitectura y Diseño',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (14,'Facultad de Artes',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (15,'Facultad de Ciencias Administrativas',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (16,'Facultad de Ciencias Humanas',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (17,'Facultad de Ciencias Sociales y Políticas',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (18,'Facultad de Deportes',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (19,'Facultad de Derecho - Mexicali',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (20,'Facultad de Enfermería',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (21,'Facultad de Idiomas',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (22,'Facultad de Ingeniería',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (23,'Facultad de Medicina',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (24,'Facultad de Odontología - Mexicali',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (25,'Facultad de Pedagogía e Innovación Educativa',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (26,'Instituto de Ingeniería',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (27,'Instituto de Investigaciones Culturales-Museo',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (28,'Instituto de Investigaciones en Ciencias Vete',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (29,'Instituto de Investigaciones Sociales',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (30,'Unidad de Ciencias de la Salud',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (31,'Facultad de Ciencias Administrativas (Extensi',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (32,'Instituto de Ciencias Agrícolas',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (33,'Facultad de Ingeniería y Negocios - Guadalupe',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (34,'Facultad de Ciencias Administrativas (Extensi',2);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (35,'Facultad de Artes (extensión Tijuana)',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (36,'Facultad de Ciencias Químicas e Ingeniería',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (37,'Facultad de Contaduría y Administración',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (38,'Facultad de Deportes (extensión Tijuana)',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (39,'Facultad de Derecho - Tijuana',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (40,'Facultad de Economía y Relaciones Internacion',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (41,'Facultad de Humanidades y Ciencias Sociales',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (42,'Facultad de Idiomas (extensión Tijuana)',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (43,'Facultad de Medicina y Psicología',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (44,'Facultad de Odontología - Tijuana',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (45,'Facultad de Turismo y Mercadotecnia',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (46,'Instituto de Investigaciones Históricas',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (47,'Unidad Universitaria en Rosarito',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (48,'Oficina de Extensión de la Cultura y Divulgac',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (49,'Facultad de Ciencias de la Ingeniería, Admini',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (50,'Facultad de Idiomas (extensión Tecate)',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (51,'Facultad de Ciencias de la Ingeniería y Tecno',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (52,'Facultad de Ciencias de la Salud Valle de las',3);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (1000,'FCQI',1000);
INSERT INTO Facultad(idFacultad,Nombre,Campus_idCampus) VALUES (1001,'FCQI_CHAFO',1001);
