INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (1,'Químico Industrial',36);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (2,'Ingeniero Químico',36);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (3,'Químico Farmacobiólogo',36);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (4,'Ingeniero en Computación',36);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (5,'Ingeniero en Electrónica',36);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (6,'Ingeniero Industrial',36);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (7,'Licenciado en Contaduria',15);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (8,'Licenciado en Administración de Empresas',15);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (9,'Licenciado en Informática',15);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (10,'Licenciado en Mercadotecnia',15);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (11,'Licenciado en Negocios Internacionales',15);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (12,'Licenciado en Gestión Turística',15);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (13,'Oceanología',5);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (14,'Licenciatura en Ciencias Ambientales',5);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (15,'Biotecnología en Acuacultura',5);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (1000,'Ingenieria en Computacion',1000);
INSERT INTO Plan_Estudio(idPlan_Estudio,Nombre,Facultad_idFacultad) VALUES (1001,'Ingenieria en diseño grafico',1001);
