INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (1,'1252819','1','Sergio','Guerra','1252819','ACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (2,'12528191','1','Sergio','Guerra','1252819','ACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (3,'125281911','1','Sergio','Guerra','1252819','ACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (11,'axmoroigres@gmail.com','Q','Sergio','Guerra','1252819','ACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (13,'omar5antonio@gmail.com','12345','Omar Antonio','Montoya Valdivia','1252892','ACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (14,'victormworld@gmail.com','ultrainstinto17','Victor Manuel','Vera Arias','1252893','ACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (15,'almp234@gmail.com','dragonballZ94','Leonardo','MelÃ©ndez','1222324','ACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (34,'1','1','1','1','1','ACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (35,'2','2','2','2','2','ACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (36,'3','3','3','3','3','ACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (37,'4','4','4','4','4','INACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (38,'5','5','5','5','5','INACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (39,'6','6','6','6','6','INACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (40,'7','7','7','7','7','INACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (41,'8','8','8','8','8','ACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (42,'Prueba','Prueba','Prueba','Prueba','Prueba','ACTIVO');
INSERT INTO Usuario(idUsuario,Correo,Password,Nombres,Apellidos,Matricula,Estatus) VALUES (NULL,'Prueba2','Prueba2','Prueba2','Prueba2','Prueba2','INACTIVO');
